# Generated by Django 5.2.8 on 2025-11-17 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='juego',
            name='genero',
        ),
        migrations.RemoveField(
            model_name='juego',
            name='plataforma',
        ),
        migrations.AddField(
            model_name='juego',
            name='genero',
            field=models.ManyToManyField(to='catalog.genero'),
        ),
        migrations.AddField(
            model_name='juego',
            name='plataforma',
            field=models.ManyToManyField(to='catalog.plataforma'),
        ),
    ]
